[[User]]
Name = "admin"
DisplayName = "Lantern Administrator"
Roles = ["Organization", "Admin"]

[[User]]
Name = "user"
DisplayName = "Test User"
Roles = ["User"]

[[Ruleset]]
Name = "playground"
DisplayName = "Playground"
OwnerRef = "admin"
HasReadAccess = "Public"

[[ContentType]]
Name = "dyn_page"
DisplayName = "Dynamic Page"
OwnerRef = "admin"
HasReadAccess = "Public"
RulesetRef = "playground"
ContentMode = "Static"
ContentCategory = "Page"

[[ContentType]]
Name = "dyn_character"
DisplayName = "Dynamic Character"
OwnerRef = "admin"
HasReadAccess = "Public"
RulesetRef = "playground"
ContentMode = "Interactive"
ContentCategory = "Character"

[[ContentType]]
Name = "dyn_item"
DisplayName = "Dynamic Item"
OwnerRef = "admin"
HasReadAccess = "Public"
RulesetRef = "playground"
ContentMode = "Static"
ContentCategory = "Item"
