[[User]]
name = "template"
displayName = "User Template"
roles = ["user"]
hasReadAccess = "inviteOnly"
iconUrl = "https:://test.com/whatever.png"

[[User]]
name = "lo"
displayName = "Lantern Official"
roles = ["organization", "official", "admin"]
hasReadAccess = "public"

[[User]]
name = "admin"
displayName = "Lantern Administrator"
roles = ["user", "admin"]
hasReadAccess = "inviteOnly"

[[User]]
name = "lucy"
displayName = "Lucy Azalea"
roles = ["user"]
hasReadAccess = "public"
