using IdGen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

public class LanternContext : DbContext
{
    public DbSet<Test> Test { get; set; }
    public DbSet<Content> Content { get; set; }
    public DbSet<ContentType> ContentType { get; set; }
    public DbSet<Layout> Layout { get; set; }
    public DbSet<Ruleset> Ruleset { get; set; }
    public DbSet<User> User { get; set; }
    public DbSet<Session> Session { get; set; }

    private string DbPath { get; }
    private IdGenerator Generator { get; }

    public LanternContext(IdGenerator generator)
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = Path.Join(path, "lantern.db");
        Console.WriteLine("Database path: " + DbPath);
        Generator = generator;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DbPath}");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var entityTpes = modelBuilder.Model.GetEntityTypes().Where(t => t.ClrType.IsAssignableTo(typeof(BaseEntity)));
        foreach (var entityType in entityTpes)
        {
            modelBuilder.Entity(entityType.ClrType)
                .Property("UpdatedAt")
                .HasConversion<DateTimeUnixEpochSecondsConverter>()
                .HasComputedColumnSql("unixepoch()", stored: true);
            modelBuilder.Entity(entityType.ClrType)
                .Property("Id")
                .ValueGeneratedOnAdd();
        }
        base.OnModelCreating(modelBuilder);
    }

    public override int SaveChanges()
    {
        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.State == EntityState.Added)
            {
                if (entry.Entity is BaseEntity entity)
                {
                    entity.Id = Generator.CreateId();
                }
            }
        }
        return base.SaveChanges();
    }
}

public class DateTimeUnixEpochSecondsConverter : ValueConverter<DateTime, long>
{
    public DateTimeUnixEpochSecondsConverter()
        : base(
            v => ((DateTimeOffset)v).ToUnixTimeSeconds(),
            v => DateTimeOffset.FromUnixTimeSeconds(v).UtcDateTime)
    {
    }
}

public class Test : BaseEntity { }

public abstract class BaseEntity
{
    public long Id { get; set; } // Autogenerated Snowflake ID
    public DateTime UpdatedAt { get; set; } // default DateTime.Now
    public required string Name { get; set; }
}

public abstract class LibraryEntity : BaseEntity
{
    public required User Owner { get; set; }
    public required Visibility Visibility { get; set; } // default Visibility.Private
}

public class Content : LibraryEntity
{
    public bool IsDynamic { get; set; }
    public ContentType? ContentType { get; set; }
    public Layout? Layout { get; set; }
    public Ruleset? Ruleset { get; set; }
    public required string[] DataIndexes { get; set; } // default []
    public required string[] DataIndexKeys { get; set; } // default []
    // public required Dictionary<string, string> Data { get; set; } TODO convert to JSON
}

public class ContentType : LibraryEntity
{
    public required Ruleset Ruleset { get; set; }
    public Layout? DefaultLayout { get; set; }
    public required string[] DataIndexKeys { get; set; } // default []
    // public required Dictionary<string, ContentTypeSchemaType> DataSchema { get; set; } TODO convert to JSON
}

public class Layout : LibraryEntity
{
    public LayoutType Type { get; set; } // default LayoutType.Content
    public required ContentType ContentType { get; set; }
    public string? Css { get; set; }
    public string? Html { get; set; }
}

public class Ruleset : LibraryEntity { }

public class User : BaseEntity
{
    public required UserGroup[] Groups { get; set; } // default [UserGroup.User]
    public string? DisplayName { get; set; }
    public string? IconUrl { get; set; }
    public string? Email { get; set; }
    public bool EmailIsVerified { get; set; }
    /// <summary>
    /// The user's hashed password. This is very sensitive information and should never be sent to a client.
    /// </summary>
    public required string PasswordHash { get; set; }
    /// <summary>
    /// The user's account recovery code. This is very sensitive information and should never be sent to a client.
    /// </summary>
    public string? RecoveryCode { get; set; }
}

public class Session
{
    public required string Id { get; set; }
    public required DateTime ExpiresAt { get; set; }
    public required User User { get; set; }
}

public enum Visibility
{
    Private = 0, Limited = 1, Friends = 2, Public = 3
}

public enum ContentTypeSchemaType
{
    String = 0, Number = 1, Boolean = 2
}

public enum LayoutType
{
    Content = 0, Character = 1,
}

public enum UserGroup
{
    User = 0, Organization = 1, Admin = 2
}
